name: quick-actions-aws-lambda-template-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  python_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Lint
      run: |
        pip install -r python/test/requirements.txt
        ruff check python/

  python_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Format
      run: |
        pip install -r python/test/requirements.txt
        ruff format python/ --check

  terraform_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terraform Format
      run: |
        terraform fmt terraform/ -check

  yaml_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: YAML Lint
      run: |
        pip install -r python/test/requirements.txt

  yaml_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: YAML Format
      run: |
        pip install -r python/test/requirements.txt

  markdown_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Markdown Format
      run: |
        pip install -r python/test/requirements.txt
  
